"""
VERTEX Central Forensic Feature Registry.
Maintains canonical definitions, types, default values, documentation,
and strict metadata contracts for all forensic features.
"""
from typing import List, Dict, Optional, Any
import json

from app.features.schema import FeatureDefinition, FeatureType
from app.features.version import FORENSIC_FEATURE_VERSION


FEATURE_REGISTRY: List[FeatureDefinition] = [
    # ── Group 1: Message Basics ───────────────────────────────────────────────
    FeatureDefinition(
        name="msg_subject_length",
        group="message_basics",
        dtype=FeatureType.INTEGER,
        description="Character length of email subject line",
        source="Subject header or tabular subject",
        extraction_function="extract_message_basics",
        default_value=0.0,
        forensic_rationale="Phishing often uses unusually long or terse urgent subjects.",
    ),
    FeatureDefinition(
        name="msg_body_length",
        group="message_basics",
        dtype=FeatureType.INTEGER,
        description="Character length of raw body content",
        source="MIME body text or tabular body",
        extraction_function="extract_message_basics",
        default_value=0.0,
        forensic_rationale="BEC emails are often concise while newsletters are lengthy.",
    ),
    FeatureDefinition(
        name="msg_body_word_count",
        group="message_basics",
        dtype=FeatureType.INTEGER,
        description="Word count in message body",
        source="MIME body text",
        extraction_function="extract_message_basics",
        default_value=0.0,
        forensic_rationale="Word density correlates with attack typology.",
    ),
    FeatureDefinition(
        name="msg_body_line_count",
        group="message_basics",
        dtype=FeatureType.INTEGER,
        description="Line break count in message body",
        source="MIME body text",
        extraction_function="extract_message_basics",
        default_value=0.0,
        forensic_rationale="Formatting style and paragraph structure.",
    ),
    FeatureDefinition(
        name="msg_has_html",
        group="message_basics",
        dtype=FeatureType.BOOLEAN,
        description="Presence of text/html MIME part or HTML tags",
        source="MIME structure or HTML detection",
        extraction_function="extract_message_basics",
        default_value=0.0,
        forensic_rationale="HTML parts enable CSS hiding and hidden hyperlinks.",
    ),
    FeatureDefinition(
        name="msg_has_plaintext",
        group="message_basics",
        dtype=FeatureType.BOOLEAN,
        description="Presence of text/plain MIME part",
        source="MIME structure",
        extraction_function="extract_message_basics",
        default_value=0.0,
        forensic_rationale="Plaintext-only messages are frequent in BEC attacks.",
    ),
    FeatureDefinition(
        name="msg_is_multipart",
        group="message_basics",
        dtype=FeatureType.BOOLEAN,
        description="MIME multipart container presence",
        source="MIME Content-Type header",
        extraction_function="extract_message_basics",
        default_value=0.0,
        forensic_rationale="Standard modern corporate emails are almost exclusively multipart.",
    ),
    FeatureDefinition(
        name="msg_mime_part_count",
        group="message_basics",
        dtype=FeatureType.INTEGER,
        description="Total count of MIME body and attachment parts",
        source="MIME tree traversal",
        extraction_function="extract_message_basics",
        default_value=1.0,
        forensic_rationale="Complex nested MIME trees may disguise embedded exploits.",
    ),
    FeatureDefinition(
        name="msg_header_count",
        group="message_basics",
        dtype=FeatureType.INTEGER,
        description="Total count of RFC822 headers",
        source="Raw email headers",
        extraction_function="extract_message_basics",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Low header counts (<5) often indicate stripped or forged headers.",
    ),
    FeatureDefinition(
        name="msg_custom_header_count",
        group="message_basics",
        dtype=FeatureType.INTEGER,
        description="Count of X- prepended custom headers",
        source="Raw email headers",
        extraction_function="extract_message_basics",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="ESP mailers and security gateways add standard X- headers.",
    ),
    FeatureDefinition(
        name="msg_encoded_header_count",
        group="message_basics",
        dtype=FeatureType.INTEGER,
        description="Count of RFC2047 encoded-word headers",
        source="Raw email headers",
        extraction_function="extract_message_basics",
        default_value=0.0,
        requires_raw_email=True,
        forensic_rationale="Obfuscated sender or subject lines often use RFC2047 encoding.",
    ),
    FeatureDefinition(
        name="msg_malformed_header_count",
        group="message_basics",
        dtype=FeatureType.INTEGER,
        description="Count of headers failing standard key:value formatting",
        source="Raw email headers",
        extraction_function="extract_message_basics",
        default_value=0.0,
        requires_raw_email=True,
        forensic_rationale="Broken headers reveal custom non-RFC compliant mail generators.",
    ),

    # ── Group 2: Header Signals ───────────────────────────────────────────────
    FeatureDefinition(
        name="hdr_from_present",
        group="header_signals",
        dtype=FeatureType.BOOLEAN,
        description="Presence of From header",
        source="Email headers",
        extraction_function="extract_header_signals",
        default_value=0.0,
        forensic_rationale="RFC5322 mandatory header.",
    ),
    FeatureDefinition(
        name="hdr_to_present",
        group="header_signals",
        dtype=FeatureType.BOOLEAN,
        description="Presence of To header",
        source="Email headers",
        extraction_function="extract_header_signals",
        default_value=0.0,
        forensic_rationale="Spam/phishing often omits direct To or puts recipients in Bcc.",
    ),
    FeatureDefinition(
        name="hdr_cc_present",
        group="header_signals",
        dtype=FeatureType.BOOLEAN,
        description="Presence of Cc header",
        source="Email headers",
        extraction_function="extract_header_signals",
        default_value=0.0,
        forensic_rationale="Distribution structure indicator.",
    ),
    FeatureDefinition(
        name="hdr_reply_to_present",
        group="header_signals",
        dtype=FeatureType.BOOLEAN,
        description="Presence of Reply-To header",
        source="Email headers",
        extraction_function="extract_header_signals",
        default_value=0.0,
        forensic_rationale="Reply-To redirection is a classic BEC/phishing mechanism.",
    ),
    FeatureDefinition(
        name="hdr_return_path_present",
        group="header_signals",
        dtype=FeatureType.BOOLEAN,
        description="Presence of Return-Path header",
        source="Email headers",
        extraction_function="extract_header_signals",
        default_value=0.0,
        forensic_rationale="Envelope sender bounce destination.",
    ),
    FeatureDefinition(
        name="hdr_message_id_present",
        group="header_signals",
        dtype=FeatureType.BOOLEAN,
        description="Presence of Message-ID header",
        source="Email headers",
        extraction_function="extract_header_signals",
        default_value=0.0,
        forensic_rationale="Legitimate MTAs virtually always inject Message-ID.",
    ),
    FeatureDefinition(
        name="hdr_date_present",
        group="header_signals",
        dtype=FeatureType.BOOLEAN,
        description="Presence of Date header",
        source="Email headers",
        extraction_function="extract_header_signals",
        default_value=0.0,
        forensic_rationale="RFC5322 mandatory header.",
    ),
    FeatureDefinition(
        name="hdr_received_present",
        group="header_signals",
        dtype=FeatureType.BOOLEAN,
        description="Presence of at least one Received header",
        source="Email headers",
        extraction_function="extract_header_signals",
        default_value=0.0,
        forensic_rationale="Received headers trace MTA relay hops.",
    ),
    FeatureDefinition(
        name="hdr_auth_results_present",
        group="header_signals",
        dtype=FeatureType.BOOLEAN,
        description="Presence of Authentication-Results header",
        source="Email headers",
        extraction_function="extract_header_signals",
        default_value=0.0,
        forensic_rationale="Injected by recipient MTA recording SPF/DKIM/DMARC verdicts.",
    ),
    FeatureDefinition(
        name="hdr_x_originating_ip_present",
        group="header_signals",
        dtype=FeatureType.BOOLEAN,
        description="Presence of X-Originating-IP or X-Sender-IP header",
        source="Email headers",
        extraction_function="extract_header_signals",
        default_value=0.0,
        forensic_rationale="Direct provenance IP injected by webmail/MTA.",
    ),
    FeatureDefinition(
        name="hdr_user_agent_present",
        group="header_signals",
        dtype=FeatureType.BOOLEAN,
        description="Presence of User-Agent header",
        source="Email headers",
        extraction_function="extract_header_signals",
        default_value=0.0,
        forensic_rationale="Client MUA signature.",
    ),
    FeatureDefinition(
        name="hdr_x_mailer_present",
        group="header_signals",
        dtype=FeatureType.BOOLEAN,
        description="Presence of X-Mailer header",
        source="Email headers",
        extraction_function="extract_header_signals",
        default_value=0.0,
        forensic_rationale="Bulk sending scripts often advertise specific X-Mailer signatures.",
    ),
    FeatureDefinition(
        name="hdr_list_unsubscribe_present",
        group="header_signals",
        dtype=FeatureType.BOOLEAN,
        description="Presence of List-Unsubscribe header",
        source="Email headers",
        extraction_function="extract_header_signals",
        default_value=0.0,
        forensic_rationale="Distinguishes mass marketing newsletters from targeted spear-phishing.",
    ),
    FeatureDefinition(
        name="hdr_received_count",
        group="header_signals",
        dtype=FeatureType.INTEGER,
        description="Count of Received headers in the envelope",
        source="Email headers",
        extraction_function="extract_header_signals",
        default_value=-1.0,
        forensic_rationale="Relay depth proxy.",
    ),
    FeatureDefinition(
        name="hdr_duplicate_security_headers",
        group="header_signals",
        dtype=FeatureType.BOOLEAN,
        description="Detection of duplicated security headers (From, Subject, Date)",
        source="Email headers",
        extraction_function="extract_header_signals",
        default_value=0.0,
        forensic_rationale="Header injection attacks exploit parser differential ambiguities.",
    ),

    # ── Group 3: Authentication Signals ───────────────────────────────────────
    FeatureDefinition(
        name="auth_spf_result",
        group="authentication_signals",
        dtype=FeatureType.CATEGORICAL,
        description="Numeric encoding of SPF result (-1=unknown, 0=none, 1=pass, 2=neutral, 3=softfail, 4=fail, 5=temperror, 6=permerror)",
        source="SPF verification or Auth-Results",
        extraction_function="extract_authentication_signals",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Sender Policy Framework authorization verdict.",
    ),
    FeatureDefinition(
        name="auth_spf_pass",
        group="authentication_signals",
        dtype=FeatureType.BOOLEAN,
        description="Binary flag indicating SPF pass verdict",
        source="SPF verification",
        extraction_function="extract_authentication_signals",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Explicit SPF authorization.",
    ),
    FeatureDefinition(
        name="auth_spf_fail",
        group="authentication_signals",
        dtype=FeatureType.BOOLEAN,
        description="Binary flag indicating SPF fail, softfail, or permerror",
        source="SPF verification",
        extraction_function="extract_authentication_signals",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Active SPF rejection.",
    ),
    FeatureDefinition(
        name="auth_dkim_result",
        group="authentication_signals",
        dtype=FeatureType.CATEGORICAL,
        description="Numeric encoding of DKIM result (-1=unknown, 0=none, 1=pass, 2=neutral, 3=fail, 4=temperror, 5=permerror)",
        source="DKIM cryptographic verification",
        extraction_function="extract_authentication_signals",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="DKIM cryptographic signature validity.",
    ),
    FeatureDefinition(
        name="auth_dkim_pass",
        group="authentication_signals",
        dtype=FeatureType.BOOLEAN,
        description="Binary flag indicating DKIM pass verdict",
        source="DKIM cryptographic verification",
        extraction_function="extract_authentication_signals",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Cryptographic proof that message was signed by claiming domain.",
    ),
    FeatureDefinition(
        name="auth_dkim_fail",
        group="authentication_signals",
        dtype=FeatureType.BOOLEAN,
        description="Binary flag indicating DKIM failure or corruption",
        source="DKIM cryptographic verification",
        extraction_function="extract_authentication_signals",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Signature tampering or forgery indicator.",
    ),
    FeatureDefinition(
        name="auth_dkim_signature_count",
        group="authentication_signals",
        dtype=FeatureType.INTEGER,
        description="Count of DKIM-Signature headers",
        source="DKIM-Signature headers",
        extraction_function="extract_authentication_signals",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Multiple signatures are common in legitimate forwarded mail.",
    ),
    FeatureDefinition(
        name="auth_dkim_body_hash_failure",
        group="authentication_signals",
        dtype=FeatureType.BOOLEAN,
        description="Flag indicating body hash bh= mismatch while header RSA passes",
        source="DKIM verification error rationale",
        extraction_function="extract_authentication_signals",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Distinguishes body content modification from header forgery.",
    ),
    FeatureDefinition(
        name="auth_dmarc_result",
        group="authentication_signals",
        dtype=FeatureType.CATEGORICAL,
        description="Numeric encoding of DMARC result (-1=unknown, 0=none, 1=pass, 2=fail, 3=temperror, 4=permerror)",
        source="DMARC evaluation",
        extraction_function="extract_authentication_signals",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Composite DMARC policy decision.",
    ),
    FeatureDefinition(
        name="auth_dmarc_pass",
        group="authentication_signals",
        dtype=FeatureType.BOOLEAN,
        description="Binary flag indicating DMARC pass",
        source="DMARC evaluation",
        extraction_function="extract_authentication_signals",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Strict identity alignment confirmed.",
    ),
    FeatureDefinition(
        name="auth_dmarc_policy",
        group="authentication_signals",
        dtype=FeatureType.CATEGORICAL,
        description="Enforcing domain policy (-1=unknown, 0=none, 1=quarantine, 2=reject)",
        source="DMARC DNS record",
        extraction_function="extract_authentication_signals",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Domain owner security posture.",
    ),
    FeatureDefinition(
        name="auth_alignment_dmarc",
        group="authentication_signals",
        dtype=FeatureType.CATEGORICAL,
        description="DMARC alignment level (-1=unknown, 0=none, 1=fail, 2=relaxed_pass, 3=strict_pass)",
        source="DMARC alignment check",
        extraction_function="extract_authentication_signals",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Alignment between RFC5322 From and DKIM/SPF identities.",
    ),

    # ── Group 4: Identity Consistency ─────────────────────────────────────────
    FeatureDefinition(
        name="ident_display_name_present",
        group="identity_consistency",
        dtype=FeatureType.BOOLEAN,
        description="Sender has a non-empty display name string",
        source="From header",
        extraction_function="extract_identity_consistency",
        default_value=0.0,
        forensic_rationale="Impersonation typically leverages deceptive display names.",
    ),
    FeatureDefinition(
        name="ident_address_parsing_failure",
        group="identity_consistency",
        dtype=FeatureType.BOOLEAN,
        description="Failed to parse RFC822 mailbox from From header",
        source="From header parsing",
        extraction_function="extract_identity_consistency",
        default_value=0.0,
        forensic_rationale="Syntax evasion attempt.",
    ),
    FeatureDefinition(
        name="ident_from_reply_to_mismatch",
        group="identity_consistency",
        dtype=FeatureType.BOOLEAN,
        description="Reply-To domain differs from From domain",
        source="From and Reply-To headers",
        extraction_function="extract_identity_consistency",
        default_value=0.0,
        forensic_rationale="Classic BEC response diversion technique.",
    ),
    FeatureDefinition(
        name="ident_from_return_path_mismatch",
        group="identity_consistency",
        dtype=FeatureType.BOOLEAN,
        description="Return-Path domain differs from From domain",
        source="From and Return-Path headers",
        extraction_function="extract_identity_consistency",
        default_value=0.0,
        forensic_rationale="Envelope vs header sender divergence.",
    ),
    FeatureDefinition(
        name="ident_sender_org_domain_mismatch",
        group="identity_consistency",
        dtype=FeatureType.BOOLEAN,
        description="From and Reply-To share different organizational root domains",
        source="PSL organizational domain lookup",
        extraction_function="extract_identity_consistency",
        default_value=0.0,
        forensic_rationale="Distinguishes subdomains within organization from external domains.",
    ),
    FeatureDefinition(
        name="ident_subdomain_depth",
        group="identity_consistency",
        dtype=FeatureType.INTEGER,
        description="Subdomain hierarchy depth of sender domain",
        source="From domain parsing",
        extraction_function="extract_identity_consistency",
        default_value=0.0,
        forensic_rationale="Attackers frequently nest subdomains (e.g. paypal.com.attacker.xyz).",
    ),
    FeatureDefinition(
        name="ident_display_name_domain_inconsistency",
        group="identity_consistency",
        dtype=FeatureType.BOOLEAN,
        description="Display name contains an email/domain that does not match sender domain",
        source="From header lexical comparison",
        extraction_function="extract_identity_consistency",
        default_value=0.0,
        forensic_rationale="Display name spoofing (e.g. 'CEO <ceo@apple.com>' from freemail).",
    ),
    FeatureDefinition(
        name="ident_freemail_sender",
        group="identity_consistency",
        dtype=FeatureType.BOOLEAN,
        description="Sender domain belongs to a public free webmail provider",
        source="Freemail domain registry",
        extraction_function="extract_identity_consistency",
        default_value=0.0,
        forensic_rationale="Common vector for unsolicited consumer attacks and CEO impersonation.",
    ),
    FeatureDefinition(
        name="ident_disposable_sender",
        group="identity_consistency",
        dtype=FeatureType.BOOLEAN,
        description="Sender domain belongs to a temporary disposable email service",
        source="Disposable domain registry",
        extraction_function="extract_identity_consistency",
        default_value=0.0,
        forensic_rationale="Burner mailboxes used for ephemeral phishing runs.",
    ),
    FeatureDefinition(
        name="ident_display_name_role_spoof",
        group="identity_consistency",
        dtype=FeatureType.BOOLEAN,
        description="Display name claims executive/corporate role while sent from freemail/subdomain",
        source="Display name keyword matching",
        extraction_function="extract_identity_consistency",
        default_value=0.0,
        forensic_rationale="High-precision BEC executive authority spoofing indicator.",
    ),

    # ── Group 5: Relay Path ───────────────────────────────────────────────────
    FeatureDefinition(
        name="relay_hop_count",
        group="relay_path",
        dtype=FeatureType.INTEGER,
        description="Total parsed Received hops in mail path",
        source="Received headers",
        extraction_function="extract_relay_path",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Delivery chain topology length.",
    ),
    FeatureDefinition(
        name="relay_unique_ip_count",
        group="relay_path",
        dtype=FeatureType.INTEGER,
        description="Count of distinct valid IP addresses observed across relay hops",
        source="Received headers",
        extraction_function="extract_relay_path",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Network diversity across transit path.",
    ),
    FeatureDefinition(
        name="relay_ipv4_count",
        group="relay_path",
        dtype=FeatureType.INTEGER,
        description="Count of IPv4 addresses found in relay hops",
        source="Received headers",
        extraction_function="extract_relay_path",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="IPv4 network footprint.",
    ),
    FeatureDefinition(
        name="relay_ipv6_count",
        group="relay_path",
        dtype=FeatureType.INTEGER,
        description="Count of IPv6 addresses found in relay hops",
        source="Received headers",
        extraction_function="extract_relay_path",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="IPv6 network footprint.",
    ),
    FeatureDefinition(
        name="relay_private_ip_count",
        group="relay_path",
        dtype=FeatureType.INTEGER,
        description="Count of RFC1918 / loopback private IPs in hops",
        source="Received headers",
        extraction_function="extract_relay_path",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Internal enterprise MTA infrastructure hops.",
    ),
    FeatureDefinition(
        name="relay_public_ip_count",
        group="relay_path",
        dtype=FeatureType.INTEGER,
        description="Count of public routable IPs in hops",
        source="Received headers",
        extraction_function="extract_relay_path",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Internet boundary transit hops.",
    ),
    FeatureDefinition(
        name="relay_malformed_ip_count",
        group="relay_path",
        dtype=FeatureType.INTEGER,
        description="Count of syntactically invalid IP candidates in hops",
        source="Received headers",
        extraction_function="extract_relay_path",
        default_value=0.0,
        requires_raw_email=True,
        forensic_rationale="Malformed headers indicative of custom forgery.",
    ),
    FeatureDefinition(
        name="relay_missing_timestamp_count",
        group="relay_path",
        dtype=FeatureType.INTEGER,
        description="Count of hops missing parseable date/time stamps",
        source="Received headers",
        extraction_function="extract_relay_path",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Forged or broken relay headers.",
    ),
    FeatureDefinition(
        name="relay_max_hop_delay_sec",
        group="relay_path",
        dtype=FeatureType.FLOAT,
        description="Maximum transit delay in seconds between consecutive hops",
        source="Received header timestamps",
        extraction_function="extract_relay_path",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Anomalous relay queues or intentional delays.",
    ),
    FeatureDefinition(
        name="relay_avg_hop_delay_sec",
        group="relay_path",
        dtype=FeatureType.FLOAT,
        description="Average transit delay in seconds across hops",
        source="Received header timestamps",
        extraction_function="extract_relay_path",
        default_value=-1.0,
        requires_raw_email=True,
        forensic_rationale="Standard internet mail transit time baseline.",
    ),
    FeatureDefinition(
        name="relay_timestamp_ordering_anomaly",
        group="relay_path",
        dtype=FeatureType.BOOLEAN,
        description="Timestamps jump backwards in time by >60 seconds along relay path",
        source="Received header timestamps",
        extraction_function="extract_relay_path",
        default_value=0.0,
        requires_raw_email=True,
        forensic_rationale="Clock skew or amateur header fabrication.",
    ),
    FeatureDefinition(
        name="relay_first_public_ip_present",
        group="relay_path",
        dtype=FeatureType.BOOLEAN,
        description="Originating public IP could be determined from relay hops",
        source="Received headers",
        extraction_function="extract_relay_path",
        default_value=0.0,
        requires_raw_email=True,
        forensic_rationale="Sender internet entry point attribution availability.",
    ),

    # ── Group 6: IP Infrastructure ────────────────────────────────────────────
    FeatureDefinition(
        name="ip_originating_present",
        group="ip_infrastructure",
        dtype=FeatureType.BOOLEAN,
        description="Originating IP address is identified and extracted",
        source="X-Originating-IP or Received hops",
        extraction_function="extract_ip_infrastructure",
        default_value=0.0,
        forensic_rationale="Sender infrastructure visibility.",
    ),
    FeatureDefinition(
        name="ip_originating_is_private",
        group="ip_infrastructure",
        dtype=FeatureType.BOOLEAN,
        description="Originating IP is in RFC1918/loopback range (-1=unknown, 0=public, 1=private)",
        source="Originating IP address",
        extraction_function="extract_ip_infrastructure",
        default_value=-1.0,
        forensic_rationale="Internal LAN submission vs public internet.",
    ),
    FeatureDefinition(
        name="ip_originating_version",
        group="ip_infrastructure",
        dtype=FeatureType.CATEGORICAL,
        description="IP version (0=none, 4=IPv4, 6=IPv6)",
        source="Originating IP address",
        extraction_function="extract_ip_infrastructure",
        default_value=0.0,
        forensic_rationale="Protocol protocol distribution.",
    ),
    FeatureDefinition(
        name="ip_originating_asn_present",
        group="ip_infrastructure",
        dtype=FeatureType.BOOLEAN,
        description="Autonomous System Number is resolved for originating IP",
        source="GeoLite2-ASN",
        extraction_function="extract_ip_infrastructure",
        default_value=0.0,
        forensic_rationale="Network operator attribution.",
    ),
    FeatureDefinition(
        name="ip_originating_org_present",
        group="ip_infrastructure",
        dtype=FeatureType.BOOLEAN,
        description="Organization name is resolved for originating IP",
        source="GeoLite2-ASN",
        extraction_function="extract_ip_infrastructure",
        default_value=0.0,
        forensic_rationale="Corporate infrastructure attribution.",
    ),
    FeatureDefinition(
        name="ip_originating_country_present",
        group="ip_infrastructure",
        dtype=FeatureType.BOOLEAN,
        description="Country code is resolved for originating IP",
        source="GeoLite2-City",
        extraction_function="extract_ip_infrastructure",
        default_value=0.0,
        forensic_rationale="Geographical routing provenance.",
    ),
    FeatureDefinition(
        name="ip_originating_cloud_hosting",
        group="ip_infrastructure",
        dtype=FeatureType.BOOLEAN,
        description="Originating IP is hosted in public cloud infrastructure (AWS/Azure/GCP/etc.)",
        source="ASN organization matching",
        extraction_function="extract_ip_infrastructure",
        default_value=0.0,
        forensic_rationale="High volume of botnet/phishing relays operate from ephemeral cloud VMs.",
    ),
    FeatureDefinition(
        name="ip_originating_confidence",
        group="ip_infrastructure",
        dtype=FeatureType.FLOAT,
        description="Confidence score (0.0 to 1.0) of originating IP identification",
        source="Heuristic source ranking",
        extraction_function="extract_ip_infrastructure",
        default_value=0.0,
        forensic_rationale="Auditability and attribution trustworthiness.",
    ),

    # ── Group 7: Domain Signals ───────────────────────────────────────────────
    FeatureDefinition(
        name="dom_sender_length",
        group="domain_signals",
        dtype=FeatureType.INTEGER,
        description="Character length of sender domain",
        source="From address domain",
        extraction_function="extract_domain_signals",
        default_value=0.0,
        forensic_rationale="Abnormally long domain names frequently indicate DGA or subdomain spoofing.",
    ),
    FeatureDefinition(
        name="dom_sender_label_count",
        group="domain_signals",
        dtype=FeatureType.INTEGER,
        description="Count of dot-delimited labels in domain",
        source="From address domain",
        extraction_function="extract_domain_signals",
        default_value=0.0,
        forensic_rationale="Domain structural complexity.",
    ),
    FeatureDefinition(
        name="dom_sender_subdomain_depth",
        group="domain_signals",
        dtype=FeatureType.INTEGER,
        description="Subdomain hierarchy depth",
        source="From address domain",
        extraction_function="extract_domain_signals",
        default_value=0.0,
        forensic_rationale="Deep subdomain nesting disguises the true registration apex.",
    ),
    FeatureDefinition(
        name="dom_sender_numeric_count",
        group="domain_signals",
        dtype=FeatureType.INTEGER,
        description="Count of numeric digits in domain name",
        source="From address domain",
        extraction_function="extract_domain_signals",
        default_value=0.0,
        forensic_rationale="DGA and disposable domains frequently feature high digit counts.",
    ),
    FeatureDefinition(
        name="dom_sender_hyphen_count",
        group="domain_signals",
        dtype=FeatureType.INTEGER,
        description="Count of hyphens in domain name",
        source="From address domain",
        extraction_function="extract_domain_signals",
        default_value=0.0,
        forensic_rationale="Brand-squatting domains frequently insert hyphens (e.g. paypal-security.com).",
    ),
    FeatureDefinition(
        name="dom_sender_digit_ratio",
        group="domain_signals",
        dtype=FeatureType.FLOAT,
        description="Ratio of numeric digits to total domain character length",
        source="From address domain",
        extraction_function="extract_domain_signals",
        default_value=0.0,
        forensic_rationale="Lexical randomness metric.",
    ),
    FeatureDefinition(
        name="dom_sender_punycode",
        group="domain_signals",
        dtype=FeatureType.BOOLEAN,
        description="Domain uses IDN punycode prefix (xn--)",
        source="From address domain",
        extraction_function="extract_domain_signals",
        default_value=0.0,
        forensic_rationale="IDN homograph attacks.",
    ),
    FeatureDefinition(
        name="dom_sender_suspicious_tld",
        group="domain_signals",
        dtype=FeatureType.BOOLEAN,
        description="Domain uses a top-level domain frequently associated with abuse (.xyz, .top, .icu, etc.)",
        source="From address domain",
        extraction_function="extract_domain_signals",
        default_value=0.0,
        forensic_rationale="High-risk TLD registration.",
    ),
    FeatureDefinition(
        name="dom_sender_cctld",
        group="domain_signals",
        dtype=FeatureType.BOOLEAN,
        description="Domain uses a 2-letter country-code TLD",
        source="From address domain",
        extraction_function="extract_domain_signals",
        default_value=0.0,
        forensic_rationale="National ccTLD vs generic gTLD categorization.",
    ),
    FeatureDefinition(
        name="dom_sender_homoglyph",
        group="domain_signals",
        dtype=FeatureType.BOOLEAN,
        description="Domain contains non-Latin homoglyphic characters resembling Latin letters",
        source="From address domain",
        extraction_function="extract_domain_signals",
        default_value=0.0,
        forensic_rationale="Direct visual spoofing detection.",
    ),
    FeatureDefinition(
        name="dom_sender_entropy",
        group="domain_signals",
        dtype=FeatureType.FLOAT,
        description="Shannon entropy (bits/char) of domain characters",
        source="From address domain",
        extraction_function="extract_domain_signals",
        default_value=0.0,
        forensic_rationale="High entropy indicates algorithmically generated domain names (DGA).",
    ),

    # ── Group 8: URL Signals ──────────────────────────────────────────────────
    FeatureDefinition(
        name="url_total_count",
        group="url_signals",
        dtype=FeatureType.INTEGER,
        description="Total count of hyperlinks extracted from message",
        source="Body plain text and HTML href/src",
        extraction_function="extract_url_signals",
        default_value=0.0,
        forensic_rationale="URL density in message.",
    ),
    FeatureDefinition(
        name="url_unique_count",
        group="url_signals",
        dtype=FeatureType.INTEGER,
        description="Count of distinct URLs",
        source="Body plain text and HTML",
        extraction_function="extract_url_signals",
        default_value=0.0,
        forensic_rationale="Repeated identical URLs vs diverse destinations.",
    ),
    FeatureDefinition(
        name="url_http_count",
        group="url_signals",
        dtype=FeatureType.INTEGER,
        description="Count of unencrypted HTTP URLs",
        source="URL scheme",
        extraction_function="extract_url_signals",
        default_value=0.0,
        forensic_rationale="Modern legitimate corporate emails rarely link to cleartext HTTP.",
    ),
    FeatureDefinition(
        name="url_https_count",
        group="url_signals",
        dtype=FeatureType.INTEGER,
        description="Count of TLS-encrypted HTTPS URLs",
        source="URL scheme",
        extraction_function="extract_url_signals",
        default_value=0.0,
        forensic_rationale="Baseline protocol metric.",
    ),
    FeatureDefinition(
        name="url_ip_literal_count",
        group="url_signals",
        dtype=FeatureType.INTEGER,
        description="Count of URLs using IP literals instead of domain names",
        source="URL host parsing",
        extraction_function="extract_url_signals",
        default_value=0.0,
        forensic_rationale="Direct IP URLs bypass domain reputation filters and are highly malicious.",
    ),
    FeatureDefinition(
        name="url_max_length",
        group="url_signals",
        dtype=FeatureType.INTEGER,
        description="Maximum character length across all URLs",
        source="URL strings",
        extraction_function="extract_url_signals",
        default_value=0.0,
        forensic_rationale="Extremely long URLs often carry serialized tracking or exploit payloads.",
    ),
    FeatureDefinition(
        name="url_avg_length",
        group="url_signals",
        dtype=FeatureType.FLOAT,
        description="Average character length across all URLs",
        source="URL strings",
        extraction_function="extract_url_signals",
        default_value=0.0,
        forensic_rationale="Mean URL complexity.",
    ),
    FeatureDefinition(
        name="url_has_query",
        group="url_signals",
        dtype=FeatureType.BOOLEAN,
        description="At least one URL contains query parameters (?key=val)",
        source="URL query component",
        extraction_function="extract_url_signals",
        default_value=0.0,
        forensic_rationale="Credential harvesting links usually carry victim tracking parameters.",
    ),
    FeatureDefinition(
        name="url_has_port",
        group="url_signals",
        dtype=FeatureType.BOOLEAN,
        description="At least one URL specifies a non-standard port (not 80/443)",
        source="URL port component",
        extraction_function="extract_url_signals",
        default_value=0.0,
        forensic_rationale="Uncommon ports indicate rogue web servers.",
    ),
    FeatureDefinition(
        name="url_has_userinfo",
        group="url_signals",
        dtype=FeatureType.BOOLEAN,
        description="At least one URL contains userinfo (@ in authority)",
        source="URL authority component",
        extraction_function="extract_url_signals",
        default_value=0.0,
        forensic_rationale="Obfuscation technique (e.g. https://google.com@evil.com).",
    ),
    FeatureDefinition(
        name="url_has_shortener",
        group="url_signals",
        dtype=FeatureType.BOOLEAN,
        description="At least one URL uses a public shortening service (bit.ly, tinyurl, etc.)",
        source="URL hostname",
        extraction_function="extract_url_signals",
        default_value=0.0,
        forensic_rationale="Shorteners obscure malicious final landing pages.",
    ),
    FeatureDefinition(
        name="url_suspicious_tld_count",
        group="url_signals",
        dtype=FeatureType.INTEGER,
        description="Count of URLs using suspicious top-level domains",
        source="URL host TLD",
        extraction_function="extract_url_signals",
        default_value=0.0,
        forensic_rationale="High-risk destination infrastructure.",
    ),

    # ── Group 9: Attachment Signals ───────────────────────────────────────────
    FeatureDefinition(
        name="att_total_count",
        group="attachment_signals",
        dtype=FeatureType.INTEGER,
        description="Total number of attachments",
        source="Email MIME attachments",
        extraction_function="extract_attachment_signals",
        default_value=0.0,
        forensic_rationale="Payload presence.",
    ),
    FeatureDefinition(
        name="att_executable_count",
        group="attachment_signals",
        dtype=FeatureType.INTEGER,
        description="Count of executable attachments (exe, scr, pif, etc.)",
        source="Attachment filename extension",
        extraction_function="extract_attachment_signals",
        default_value=0.0,
        forensic_rationale="Direct binary malware payload.",
    ),
    FeatureDefinition(
        name="att_archive_count",
        group="attachment_signals",
        dtype=FeatureType.INTEGER,
        description="Count of archive attachments (zip, rar, 7z, tar, etc.)",
        source="Attachment filename extension",
        extraction_function="extract_attachment_signals",
        default_value=0.0,
        forensic_rationale="Archives are used to evade gateway inspection.",
    ),
    FeatureDefinition(
        name="att_script_count",
        group="attachment_signals",
        dtype=FeatureType.INTEGER,
        description="Count of script attachments (js, vbs, ps1, bat, etc.)",
        source="Attachment filename extension",
        extraction_function="extract_attachment_signals",
        default_value=0.0,
        forensic_rationale="Living-off-the-land script droppers.",
    ),
    FeatureDefinition(
        name="att_macro_count",
        group="attachment_signals",
        dtype=FeatureType.INTEGER,
        description="Count of macro-enabled Office documents (docm, xlsm, pptm, etc.)",
        source="Attachment filename extension",
        extraction_function="extract_attachment_signals",
        default_value=0.0,
        forensic_rationale="VBA macro malware delivery.",
    ),
    FeatureDefinition(
        name="att_double_extension_count",
        group="attachment_signals",
        dtype=FeatureType.INTEGER,
        description="Count of attachments with deceptive double extensions (e.g. invoice.pdf.exe)",
        source="Attachment filename",
        extraction_function="extract_attachment_signals",
        default_value=0.0,
        forensic_rationale="Classic evasion exploiting Windows hide-known-extensions behavior.",
    ),
    FeatureDefinition(
        name="att_mime_mismatch_count",
        group="attachment_signals",
        dtype=FeatureType.INTEGER,
        description="Count of attachments whose declared MIME type contradicts their file extension",
        source="Content-Type vs filename",
        extraction_function="extract_attachment_signals",
        default_value=0.0,
        forensic_rationale="MIME smuggling / gateway bypass attempts.",
    ),
    FeatureDefinition(
        name="att_max_size_bytes",
        group="attachment_signals",
        dtype=FeatureType.INTEGER,
        description="Maximum attachment size in bytes",
        source="Attachment metadata",
        extraction_function="extract_attachment_signals",
        default_value=0.0,
        forensic_rationale="Zero-byte placeholders or bloated files designed to exceed scanning limits.",
    ),
    FeatureDefinition(
        name="att_rfc822_count",
        group="attachment_signals",
        dtype=FeatureType.INTEGER,
        description="Count of embedded RFC822 message attachments (.eml)",
        source="Attachment MIME type",
        extraction_function="extract_attachment_signals",
        default_value=0.0,
        forensic_rationale="Phishing via attached email wrappers.",
    ),

    # ── Group 10: Content Structure ───────────────────────────────────────────
    FeatureDefinition(
        name="cnt_uppercase_ratio",
        group="content_structure",
        dtype=FeatureType.FLOAT,
        description="Ratio of uppercase characters to total alphabetic characters",
        source="Subject and body text",
        extraction_function="extract_content_structure",
        default_value=0.0,
        forensic_rationale="Aggressive emotional manipulation and urgency.",
    ),
    FeatureDefinition(
        name="cnt_digit_ratio",
        group="content_structure",
        dtype=FeatureType.FLOAT,
        description="Ratio of numeric digits to total characters",
        source="Subject and body text",
        extraction_function="extract_content_structure",
        default_value=0.0,
        forensic_rationale="High digit counts in body correlate with account codes or obfuscation.",
    ),
    FeatureDefinition(
        name="cnt_punctuation_ratio",
        group="content_structure",
        dtype=FeatureType.FLOAT,
        description="Ratio of punctuation marks to total characters",
        source="Subject and body text",
        extraction_function="extract_content_structure",
        default_value=0.0,
        forensic_rationale="Punctuation density anomaly.",
    ),
    FeatureDefinition(
        name="cnt_exclamation_count",
        group="content_structure",
        dtype=FeatureType.INTEGER,
        description="Total count of exclamation marks (!)",
        source="Subject and body text",
        extraction_function="extract_content_structure",
        default_value=0.0,
        forensic_rationale="Psychological pressure indicator.",
    ),
    FeatureDefinition(
        name="cnt_question_count",
        group="content_structure",
        dtype=FeatureType.INTEGER,
        description="Total count of question marks (?)",
        source="Subject and body text",
        extraction_function="extract_content_structure",
        default_value=0.0,
        forensic_rationale="Probing inquiries common in preliminary BEC reconnaissance.",
    ),
    FeatureDefinition(
        name="cnt_currency_symbol_count",
        group="content_structure",
        dtype=FeatureType.INTEGER,
        description="Count of currency symbols ($, €, £, ¥, ₹)",
        source="Subject and body text",
        extraction_function="extract_content_structure",
        default_value=0.0,
        forensic_rationale="Financial transaction lure indicator.",
    ),
    FeatureDefinition(
        name="cnt_excessive_capitalization",
        group="content_structure",
        dtype=FeatureType.BOOLEAN,
        description="Uppercase ratio exceeds 35% across substantial alphabetic volume",
        source="Subject and body text",
        extraction_function="extract_content_structure",
        default_value=0.0,
        forensic_rationale="Shouting urgency cues.",
    ),
    FeatureDefinition(
        name="cnt_repeated_chars_detected",
        group="content_structure",
        dtype=FeatureType.BOOLEAN,
        description="Four or more consecutive identical characters (e.g. Freeeee, !!!!)",
        source="Subject and body text",
        extraction_function="extract_content_structure",
        default_value=0.0,
        forensic_rationale="Spam colloquialisms.",
    ),
    FeatureDefinition(
        name="cnt_whitespace_anomaly",
        group="content_structure",
        dtype=FeatureType.BOOLEAN,
        description="Excessive consecutive blank lines (>=5) or irregular spacing",
        source="Subject and body text",
        extraction_function="extract_content_structure",
        default_value=0.0,
        forensic_rationale="Whitespace padding pushes suspicious content below standard preview windows.",
    ),
    FeatureDefinition(
        name="cnt_html_text_ratio",
        group="content_structure",
        dtype=FeatureType.FLOAT,
        description="Ratio of HTML markup characters to visible plain text characters",
        source="HTML vs body text",
        extraction_function="extract_content_structure",
        default_value=0.0,
        forensic_rationale="Heavy HTML scaffolding with minimal visible text indicates image-only phishing.",
    ),
    FeatureDefinition(
        name="cnt_hidden_text_detected",
        group="content_structure",
        dtype=FeatureType.BOOLEAN,
        description="Detection of hidden CSS styles (display:none, font-size:0, white-on-white)",
        source="HTML content",
        extraction_function="extract_content_structure",
        default_value=0.0,
        forensic_rationale="Adversarial text injection designed to fool Bayesian/NLP models.",
    ),
    FeatureDefinition(
        name="cnt_unicode_anomaly",
        group="content_structure",
        dtype=FeatureType.BOOLEAN,
        description="Detection of zero-width characters, RTL overrides, or non-ASCII subject chars",
        source="Subject and body text",
        extraction_function="extract_content_structure",
        default_value=0.0,
        forensic_rationale="Steganographic or direction-override evasion tricks.",
    ),

    # ── Group 11: BEC & Phish Semantic Cues ───────────────────────────────────
    FeatureDefinition(
        name="bec_urgency_score",
        group="bec_phish_signals",
        dtype=FeatureType.FLOAT,
        description="Count of high-urgency keywords and temporal deadlines",
        source="Subject and body text",
        extraction_function="extract_bec_phish_signals",
        default_value=0.0,
        forensic_rationale="Pretexting urgency to bypass employee scrutiny.",
    ),
    FeatureDefinition(
        name="bec_credential_harvest_cues",
        group="bec_phish_signals",
        dtype=FeatureType.FLOAT,
        description="Count of credential update and account verification phrases",
        source="Subject and body text",
        extraction_function="extract_bec_phish_signals",
        default_value=0.0,
        forensic_rationale="Credential phishing attack signature.",
    ),
    FeatureDefinition(
        name="bec_payment_request_cues",
        group="bec_phish_signals",
        dtype=FeatureType.FLOAT,
        description="Count of direct financial transfer phrases",
        source="Subject and body text",
        extraction_function="extract_bec_phish_signals",
        default_value=0.0,
        forensic_rationale="Financial fraud / wire fraud demands.",
    ),
    FeatureDefinition(
        name="bec_account_verification_cues",
        group="bec_phish_signals",
        dtype=FeatureType.FLOAT,
        description="Count of security check and account confirmation terms",
        source="Subject and body text",
        extraction_function="extract_bec_phish_signals",
        default_value=0.0,
        forensic_rationale="Account suspension / KYC lure phrases.",
    ),
    FeatureDefinition(
        name="bec_secrecy_cues",
        group="bec_phish_signals",
        dtype=FeatureType.FLOAT,
        description="Count of confidentiality and non-disclosure commands",
        source="Subject and body text",
        extraction_function="extract_bec_phish_signals",
        default_value=0.0,
        forensic_rationale="Isolating victims from verification channels (e.g. 'keep this strictly confidential').",
    ),
    FeatureDefinition(
        name="bec_bank_change_cues",
        group="bec_phish_signals",
        dtype=FeatureType.FLOAT,
        description="Count of bank account alteration phrases",
        source="Subject and body text",
        extraction_function="extract_bec_phish_signals",
        default_value=0.0,
        forensic_rationale="Vendor email compromise / invoice re-routing fraud.",
    ),
    FeatureDefinition(
        name="bec_gift_card_cues",
        group="bec_phish_signals",
        dtype=FeatureType.FLOAT,
        description="Count of gift card / retail voucher requests",
        source="Subject and body text",
        extraction_function="extract_bec_phish_signals",
        default_value=0.0,
        forensic_rationale="Unrecoverable consumer gift card fraud.",
    ),
    FeatureDefinition(
        name="bec_wire_transfer_cues",
        group="bec_phish_signals",
        dtype=FeatureType.FLOAT,
        description="Count of wire, SWIFT, IBAN, and routing code cues",
        source="Subject and body text",
        extraction_function="extract_bec_phish_signals",
        default_value=0.0,
        forensic_rationale="Direct bank wire transfer vectors.",
    ),
    FeatureDefinition(
        name="bec_invoice_cues",
        group="bec_phish_signals",
        dtype=FeatureType.FLOAT,
        description="Count of billing, invoice, and receipt references",
        source="Subject and body text",
        extraction_function="extract_bec_phish_signals",
        default_value=0.0,
        forensic_rationale="Accounts payable impersonation.",
    ),
    FeatureDefinition(
        name="bec_executive_terms_count",
        group="bec_phish_signals",
        dtype=FeatureType.FLOAT,
        description="Count of C-level and board executive titles",
        source="Subject and body text",
        extraction_function="extract_bec_phish_signals",
        default_value=0.0,
        forensic_rationale="Hierarchical authority exploitation.",
    ),
    FeatureDefinition(
        name="bec_login_terms_count",
        group="bec_phish_signals",
        dtype=FeatureType.FLOAT,
        description="Count of login and portal navigation keywords",
        source="Subject and body text",
        extraction_function="extract_bec_phish_signals",
        default_value=0.0,
        forensic_rationale="Credential entry lure terms.",
    ),
    FeatureDefinition(
        name="bec_password_terms_count",
        group="bec_phish_signals",
        dtype=FeatureType.FLOAT,
        description="Count of password, PIN, and 2FA token keywords",
        source="Subject and body text",
        extraction_function="extract_bec_phish_signals",
        default_value=0.0,
        forensic_rationale="Direct secret harvesting terms.",
    ),
]

_FEATURE_MAP: Dict[str, FeatureDefinition] = {f.name: f for f in FEATURE_REGISTRY}


def get_feature_registry() -> List[FeatureDefinition]:
    """Returns all registered forensic feature definitions."""
    return list(FEATURE_REGISTRY)


def get_feature_names() -> List[str]:
    """Returns sorted or canonical list of feature names in the registry."""
    return [f.name for f in FEATURE_REGISTRY]


def get_feature_by_name(name: str) -> Optional[FeatureDefinition]:
    """Retrieves feature definition by name."""
    return _FEATURE_MAP.get(name)


def get_features_by_group(group: str) -> List[FeatureDefinition]:
    """Retrieves all feature definitions belonging to a specific group."""
    return [f for f in FEATURE_REGISTRY if f.group == group]


def export_feature_schema_json(indent: int = 2) -> str:
    """Exports entire registry as JSON for frontend, schemas, or docs."""
    data = [f.to_dict() for f in FEATURE_REGISTRY]
    return json.dumps(data, indent=indent)
