"""Add D6 threat intelligence tables

Revision ID: 32183ae95dc8
Revises: c1b2a3d4e5f6
Create Date: 2026-09-09 01:44:40.218656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32183ae95dc8'
down_revision: Union[str, Sequence[str], None] = 'c1b2a3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_raw_payloads_email_id'), table_name='email_raw_payloads')
    op.drop_index(op.f('idx_raw_payloads_sha256'), table_name='email_raw_payloads')
    op.drop_constraint(op.f('uq_email_raw_payloads_email_id'), 'email_raw_payloads', type_='unique')
    op.create_index(op.f('ix_email_raw_payloads_email_id'), 'email_raw_payloads', ['email_id'], unique=True)
    op.create_index(op.f('ix_email_raw_payloads_sha256'), 'email_raw_payloads', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_raw_payloads_sha256'), table_name='email_raw_payloads')
    op.drop_index(op.f('ix_email_raw_payloads_email_id'), table_name='email_raw_payloads')
    op.create_unique_constraint(op.f('uq_email_raw_payloads_email_id'), 'email_raw_payloads', ['email_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_raw_payloads_sha256'), 'email_raw_payloads', ['sha256'], unique=False)
    op.create_index(op.f('idx_raw_payloads_email_id'), 'email_raw_payloads', ['email_id'], unique=False)
    # ### end Alembic commands ###
