"""Add graph nodes and edges tables for Phase D7

Revision ID: 949b3fb1cb50
Revises: 32183ae95dc8
Create Date: 2026-09-09 18:35:12.122695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949b3fb1cb50'
down_revision: Union[str, Sequence[str], None] = '32183ae95dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('canonical_value', sa.String(length=255), nullable=False),
    sa.Column('display_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id'),
    sa.UniqueConstraint('node_type', 'canonical_value', name='uq_node_type_canonical_value')
    )
    op.create_table('graph_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('edge_id', sa.String(length=255), nullable=False),
    sa.Column('source_node_id', sa.String(length=255), nullable=False),
    sa.Column('target_node_id', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('source_email_id', sa.Integer(), nullable=True),
    sa.Column('source_case_id', sa.Integer(), nullable=True),
    sa.Column('source_provider', sa.String(length=100), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=True),
    sa.Column('evidence_reference', sa.String(length=255), nullable=True),
    sa.Column('is_inferred', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['source_email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.node_id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edge_id')
    )
    op.create_index('ix_graph_edges_relationship_type', 'graph_edges', ['relationship_type'], unique=False)
    op.create_index('ix_graph_edges_source_case', 'graph_edges', ['source_case_id'], unique=False)
    op.create_index('ix_graph_edges_source_email', 'graph_edges', ['source_email_id'], unique=False)
    op.create_index('ix_graph_edges_source_node', 'graph_edges', ['source_node_id'], unique=False)
    op.create_index('ix_graph_edges_target_node', 'graph_edges', ['target_node_id'], unique=False)
    # Add a unique constraint for deterministic (observed) edges to prevent duplicates
    op.create_index('ux_graph_edges_observed', 'graph_edges',
                    ['source_node_id', 'target_node_id', 'relationship_type'],
                    unique=True,
                    postgresql_where=sa.text("is_inferred = false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_graph_edges_observed', table_name='graph_edges', postgresql_where=sa.text("is_inferred = false"))
    op.drop_index('ix_graph_edges_target_node', table_name='graph_edges')
    op.drop_index('ix_graph_edges_source_node', table_name='graph_edges')
    op.drop_index('ix_graph_edges_source_email', table_name='graph_edges')
    op.drop_index('ix_graph_edges_source_case', table_name='graph_edges')
    op.drop_index('ix_graph_edges_relationship_type', table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_table('graph_nodes')
    # ### end Alembic commands ###